### ISSUE TITLE
Pet store sample throw

### ISSUE THREAD

**Issue by m1ky91** [awslabs/aws-serverless-java-container#130]
* Framework version: 1.0
* Implementations: Spark

## Scenario
I have a problem with Pet Store Serverless Spark example. I have just cloned the example and deploy it to AWS Lambda but it throws a NPE. With SAM Local I have no problem. What's wrong?
## Steps to reproduce
![immagine](https://user-images.githubusercontent.com/12275263/36858157-b29ed2fa-1d7a-11e8-837e-cbbbb42b75a1.png)

## Full log output
```
START RequestId: 67a92152-1d26-11e8-a10d-a3c1a71f6fc3 Version: $LATEST
[2018-03-01 07:59:02.875] NO-REQUEST-ID INFO c.a.s.p.i.LambdaContainerHandler - Starting Lambda Container Handler
[2018-03-01 07:59:02.952] NO-REQUEST-ID INFO c.a.s.p.s.e.LambdaEmbeddedServer - Spark called configureWebSockets. However, web sockets are not supported
[2018-03-01 07:59:02.952] NO-REQUEST-ID INFO c.a.s.p.s.e.LambdaEmbeddedServer - Starting Spark server, ignoring port and host
[2018-03-01 07:59:02.953] NO-REQUEST-ID INFO c.a.s.p.s.e.LambdaEmbeddedServer - Called join method, nothing to do here since Lambda only runs a single event per container
java.lang.NullPointerException
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.cleanUri(AwsProxyHttpServletRequest.java:709)
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getRequestURI(AwsProxyHttpServletRequest.java:249)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:99)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:197)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:214)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:212)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:76)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:163)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:198)
at com.amazonaws.serverless.sample.spark.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
END RequestId: 67a92152-1d26-11e8-a10d-a3c1a71f6fc3
REPORT RequestId: 67a92152-1d26-11e8-a10d-a3c1a71f6fc3 Duration: 1935.22 ms Billed Duration: 2000 ms Memory Size: 320 MB Max Memory Used: 59 MB
[2018-03-01 07:59:04.634] 67a92152-1d26-11e8-a10d-a3c1a71f6fc3 ERROR c.a.s.p.i.LambdaContainerHandler - Error while handling request
java.lang.NullPointerException: null
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.cleanUri(AwsProxyHttpServletRequest.java:709)
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getRequestURI(AwsProxyHttpServletRequest.java:249)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:99)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:197)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:214)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:212)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:76)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:163)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:198)
at com.amazonaws.serverless.sample.spark.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
[2018-03-01 07:59:04.673] 67a92152-1d26-11e8-a10d-a3c1a71f6fc3 ERROR c.a.s.p.AwsProxyExceptionHandler - Called exception handler for:
java.lang.NullPointerException: null
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.cleanUri(AwsProxyHttpServletRequest.java:709)
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getRequestURI(AwsProxyHttpServletRequest.java:249)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:99)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:197)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:214)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:212)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.handleRequest(SparkLambdaContainerHandler.java:76)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:163)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:198)
at com.amazonaws.serverless.sample.spark.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
```

**Comment by SAPessi** [comment]
I have just tested myself deploying to Lambda and couldn't replicate. Let me dig deeper. I'll update this issue once I figured it out.

**Comment by SAPessi** [comment]
How are you calling the application? Curl or browser? Can you paste the command you are using?

**Comment by m1ky91** [comment]
I am testing the lambda function with the test functionality on the console and also linking an API Gateway to it. But in the both scenarios I have the same response.

**Comment by SAPessi** [comment]
Can you paste the test event JSON here? The framework is not handling null paths gracefully - I have fixed that. However, this should work with a non-null path. With your test event, I can also add a unit test to make sure this is checked in the future.

**Comment by m1ky91** [comment]
Below the json. It is the Classic hello world json:
{
"key3":"value3", 
"key2":'"value2", 
"key1":"value1" 
} 
This is the response:
{
  "statusCode": 502,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": "{\"message\":\"Gateway timeout\"}",
  "base64Encoded": false
}

**Comment by m1ky91** [comment]
I have the same response linking API Gateway and calling GET /pets

**Comment by SAPessi** [comment]
Ah, that would be why. You need to invoke this function with an API Gateway proxy event. Your test event should look like this:
```
{
  "body": "",
  "resource": "/{proxy+}",
  "requestContext": {
    "resourceId": "123456",
    "apiId": "1234567890",
    "resourcePath": "/{proxy+}",
    "httpMethod": "GET",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "accountId": "123456789012",
    "identity": {
      "apiKey": null,
      "userArn": null,
      "cognitoAuthenticationType": null,
      "caller": null,
      "userAgent": "Custom User Agent String",
      "user": null,
      "cognitoIdentityPoolId": null,
      "cognitoIdentityId": null,
      "cognitoAuthenticationProvider": null,
      "sourceIp": "127.0.0.1",
      "accountId": null
    },
    "stage": "prod"
  },
  "queryStringParameters": {},
  "headers": {
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "Accept-Language": "en-US,en;q=0.8",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "User-Agent": "Custom User Agent String",
    "Accept-Encoding": "gzip, deflate, sdch"
  },
  "pathParameters": {
    "proxy": "pets"
  },
  "httpMethod": "GET",
  "stageVariables": {},
  "path": "/pets"
}
```

This is what API Gateway (and SAM local) send to your Lambda function. When you configure API Gateway to connect to your Lambda function, make sure that you configure it with an proxy integration. The easiest way to deploy the application, is to use SAM. The instructions are in the [readme file of the sample](https://github.com/awslabs/aws-serverless-java-container/tree/master/samples/spark/pet-store).

Regardless, I've also added a fix to handle null paths gracefully.

**Comment by m1ky91** [comment]
Thanks but I can't test it now. I am going to do this later and come back to you. Thanks a lot.

**Comment by m1ky91** [comment]
Thank you Stefano now everything works correctly. Keep up the good work.

**Comment by SAPessi** [comment]
Great. I'll close this for now. The fix is committed and will go out with the next release.
