### ISSUE TITLE
JSON String as a Query Parameter throws error

### ISSUE THREAD

**Issue by aldilaff** [awslabs/aws-serverless-java-container#154]
* Framework version: 1.1
* Implementations: Jersey 

## Scenario

I have a GET endpoint that takes in a String query parameter:
```java

 @GET
    @Path("/search")
    @Produces(MediaType.APPLICATION_JSON)
    public Response list(@QueryParam("query") String queryStr) throws IOException {
        Map<String, String> response = new HashMap<>();
        response.put("body", queryStr);
        return Response.status(200).entity(response).build();
    }
}
```
When the endpoint is called with a simple string as a parameter it works as expected. For example `.../search?query=helloWorld` would work as expected. However, when the function is called with a JSON string as a parameter I am seeing an IllegalArgumentException. Making this call `.../search?query={"name":"faisal"}` would throw this error:

```
java.lang.IllegalArgumentException: Illegal character """ at position 7 is not allowed as a start of a name in a path template "query={"name":"faisal"}".
```
## Expected behavior
The JSON string should be parsed as a string.

## Actual behavior
The JSON string causes an IllegalArgumentException.

## Steps to reproduce

1. Define a GET endpoint that takes in a string as a query parameter
2. Call endpoint with the parameter set to a JSON string.

## Full log output
```
4310 [main] ERROR com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Error while handling request
java.lang.IllegalArgumentException: Illegal character """ at position 7 is not allowed as a start of a name in a path template "query={"name":"faisal"}".
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parseName(UriTemplateParser.java:331)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parse(UriTemplateParser.java:256)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.<init>(UriTemplateParser.java:115)
	at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1004)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:970)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
	at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.servletRequestToContainerRequest(JerseyHandlerFilter.java:141)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.doFilter(JerseyHandlerFilter.java:86)
	at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
	at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:171)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:75)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200)
	at com.lithium.tocoma.reach.handlers.AssetHandler.handleRequest(AssetHandler.java:23)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
4316 [main] ERROR com.amazonaws.serverless.proxy.AwsProxyExceptionHandler - Called exception handler for:
java.lang.IllegalArgumentException: Illegal character """ at position 7 is not allowed as a start of a name in a path template "query={"name":"faisal"}".
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parseName(UriTemplateParser.java:331)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parse(UriTemplateParser.java:256)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.<init>(UriTemplateParser.java:115)
	at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1004)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:970)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
	at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.servletRequestToContainerRequest(JerseyHandlerFilter.java:141)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.doFilter(JerseyHandlerFilter.java:86)
	at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
	at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:171)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:75)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200)
	at com.lithium.tocoma.reach.handlers.AssetHandler.handleRequest(AssetHandler.java:23)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
java.lang.IllegalArgumentException: Illegal character """ at position 7 is not allowed as a start of a name in a path template "query={"name":"faisal"}".
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parseName(UriTemplateParser.java:331)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.parse(UriTemplateParser.java:256)
	at org.glassfish.jersey.uri.internal.UriTemplateParser.<init>(UriTemplateParser.java:115)
	at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1004)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:970)
	at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
	at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.servletRequestToContainerRequest(JerseyHandlerFilter.java:141)
	at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.doFilter(JerseyHandlerFilter.java:86)
	at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
	at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:171)
	at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:75)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200)
	at com.lithium.tocoma.reach.handlers.AssetHandler.handleRequest(AssetHandler.java:23)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
```

**Comment by SAPessi** [comment]
Hey @aldilaff, you should URLEncode the paraters - this is how a browser would behave.

**Comment by aldilaff** [comment]
Hi @SAPessi, thank you for the reply. 

I tried with `.../search/query%3D%7B%22name%22%3A%22faisal%22%7D` and i'm getting the same error:

```
java.lang.IllegalArgumentException: Illegal character """ at position 40 is not allowed as a start of a name in a path template "/hello-name-test-resource/search/query={"name":"faisal"}".
at org.glassfish.jersey.uri.internal.UriTemplateParser.parseName(UriTemplateParser.java:331)
at org.glassfish.jersey.uri.internal.UriTemplateParser.parse(UriTemplateParser.java:256)
at org.glassfish.jersey.uri.internal.UriTemplateParser.<init>(UriTemplateParser.java:115)
at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1004)
at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:964)
at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914)
at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831)
at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.servletRequestToContainerRequest(JerseyHandlerFilter.java:141)
at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.doFilter(JerseyHandlerFilter.java:86)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207)
at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:171)
at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:75)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200)
at com.example.hello.name.Name.handleRequest(Name.java:34)
```

I initially saw the issue while using [AWS SAM CLI](https://github.com/awslabs/aws-sam-cli) locally. However, I deployed to AWS and I am still seeing the error.

**Comment by SAPessi** [comment]
You cannot have json as part of the path. You'd request should go to `/search?query=%7B%22name%22%3A%22faisal%22%7D`. Please keep in mind that it is not best practice to send JSON data in a query string parameter - I'd do it only if it's absolutely necessary. It would be much better to send parameters individually. for example: `/search?name=faisal`.

**Comment by aldilaff** [comment]
Good catch, sorry about that.
I tried with `/search?query=%7B%22name%22%3A%22faisal%22%7D` and I am getting the same error:
```
java.lang.IllegalArgumentException: Illegal character """ at position 7 is not allowed as a start of a name in a path template "query={"name":"faisal"}".
at org.glassfish.jersey.uri.internal.UriTemplateParser.parseName(UriTemplateParser.java:331)
at org.glassfish.jersey.uri.internal.UriTemplateParser.parse(UriTemplateParser.java:256)
at org.glassfish.jersey.uri.internal.UriTemplateParser.<init>(UriTemplateParser.java:115)
at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1004)
...
```
We are currently working around it by switching the endpoint to a PUT and sending in the JSON data in the body but I was wondering if anyone else had the same issue?

Thank you again @SAPessi for the help!

**Comment by SAPessi** [comment]
I suspect it may have something to do with API Gateway/SAM CLI url-decoding the parameters and the library not re-encoding them before passing them to the framework. I'll mark it as a bug and address it with the next release.

**Comment by SAPessi** [comment]
I did some testing on this. I can confirm that API Gateway automatically decodes the query string parameter values. However, it also escapes them to fit in the JSON values. Your parameter `%7B%22name%22%3A%22faisal%22%7D` appears in the `queryStringParameters` map as `{\"name\":\"faisal\"}`. If I just re-encode the content it will come through as `%7B%5C%22name%5C%22%3A%5C%22faisal%5C%22%7D`, which is not what you'd expect.

**Comment by SAPessi** [comment]
Hey @aldilaff, any chance you can test with the `1.2-SNAPSHOT` in the `core` branch of this repo? Simply download or clone the `core` branch to your local box then run `mvn install`. Once that's installed in your local cache you should be able to just change the dependency in your pom to `1.2-SNAPSHOT`

**Comment by SAPessi** [comment]
release 1.1.1 is going out to maven central
