### ISSUE TITLE
NullpointerException if calling Lambda without parameters

### ISSUE THREAD

**Issue by Juchar** [awslabs/aws-serverless-java-container#173]
* Framework version: 1.1.3
* Implementations: Spring Boot (version of `spring-boot-starter-parent`:`2.0.3.RELEASE`, therefore using spring `5.0.7.RELEASE`)

## Scenario
I have implemented a custom error controller with the possibility to include the trace if the query parameter `trace` is specified:

```java
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.web.servlet.error.ErrorAttributes;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.ServletWebRequest;

/**
 * Controller for returning errors in an api (json) friendly manner.
 */
@RestController
@RequestMapping("/error")
public class ErrorController implements org.springframework.boot.web.servlet.error.ErrorController {

  private final ErrorAttributes errorAttributes;

  /**
   * Create a new error controller.
   *
   * @param errorAttributes Used to access the error attributes of a request.
   */
  @Autowired
  public ErrorController(ErrorAttributes errorAttributes) {
    Assert.notNull(errorAttributes, "ErrorAttributes must not be null");
    this.errorAttributes = errorAttributes;
  }

  @Override
  public String getErrorPath() {
    return "/error";
  }

  /**
   * Handle the request to "/error".
   *
   * @param aRequest The request to handle.
   *
   * @return The according response.
   */
  @RequestMapping
  public Map<String, Object> error(HttpServletRequest aRequest) {
    Map<String, Object> body = getErrorAttributes(aRequest, shouldIncludeTrace(aRequest));
    String trace = (String) body.get("trace");
    if (trace != null) {
      String[] lines = trace.split("\n\t");
      body.put("trace", lines);
    }
    return body;
  }

  /**
   * Check if the stacktrace should be included. It will be included if a parameter
   * <code>trace</code> is present having a value different than <code>false</code>, e.g.
   * <code>?trace</code> or <code>?trace=true</code>.
   *
   * @param request The request to check.
   *
   * @return <code>true</code> if the stacktrace should be included, <code>false</code> else.
   */
  private boolean shouldIncludeTrace(HttpServletRequest request) {
    String parameter = request.getParameter("trace");
    return parameter != null && !"false".equals(parameter.toLowerCase());
  }

  /**
   * Get the error attributes as a map.
   *
   * @param aRequest The request to get the attributes from.
   * @param includeStackTrace <code>true</code> if the stacktrace should be included,
   *     <code>false</code> else.
   *
   * @return The error attributes as a map.
   */
  private Map<String, Object> getErrorAttributes(HttpServletRequest aRequest,
      boolean includeStackTrace) {
    ServletWebRequest requestAttributes = new ServletWebRequest(aRequest);
    return errorAttributes.getErrorAttributes(requestAttributes, includeStackTrace);
  }
}
```

Afterwards I call my lambda without any parameters, this produces an error.

## Expected behavior
I expect to get a JSON error response without the stacktrace.

## Actual behavior
A `NullpointerException` happens.

## Steps to reproduce
Call a lambda without any parameters that has parameters specified with default values.
This seems to trigger the error page. There try to get a parameter, in my case `tace`.

## Full log output
> Caused by: java.lang.NullPointerException
> at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getQueryParamValue(AwsProxyHttpServletRequest.java:819)
> at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getParameter(AwsProxyHttpServletRequest.java:445)
> at com.my.lambda.ErrorController.shouldIncludeTrace(ErrorController.java:65)
> at com.my.lambda.ErrorController.error(ErrorController.java:46)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
> at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
> at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
> at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
> at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
> at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)

## Additional Information
The exception seems to happen on this line of code inside the `AwsProxyHttpServletRequest`:

`for (String k : request.getQueryStringParameters().keySet()) {`

For me it means that either `request` is null or `getQueryStringParameters()` returns null.
After digging in it is quite clear that `getQueryStringParameters()` can not return null as it is initialized to a new `HashMap` inside the `AwsProxyRequest` constructor.

By consequence it seems (strangely) that the `request` member variable is null.

Unfortunately I could not find out why.

**Comment by Juchar** [comment]
Ok, seems that this is the same issue as in #172  and has been resolved with `1.2-SNAPSHOT`.
