### ISSUE TITLE
Autowired @Value from Spring Config

### ISSUE THREAD

**Issue by kart2018** [awslabs/aws-serverless-java-container#193]
* Framework version: 2.0.3
* Implementations: Spring Boot 

Scenario
I am looking to get the properties value from Spring Config -> Artifactory, in my DB config i have used the Autowired @Value , looks like the properties is not able to find by LambdaHandler.

I am getting the below error,

at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1350)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580)

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.util.dbutil' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1509)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)

My Lambda Handler is below,

public class TestLambdaHandler implements RequestStreamHandler {

    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    static {
        try {
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
        } catch (ContainerInitializationException e) {
            // Re-throw the exception to force another cold start
            e.printStackTrace();
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
        handler.proxyStream(inputStream, outputStream, context);

        // just in case it wasn't closed by the mapper
        outputStream.close();
    }
}

Need your help to fix this code.

**Comment by SAPessi** [comment]
Hi @kart2018, we have not tested the framework with SpringBoot 2.x - see issue #181. Can you paste here some more code? Specifically where the `@Autowired` property is declared and the bean it should get the value from?

**Comment by jaympatel1893** [comment]
How can I help?

**Comment by sapessi** [comment]
@kart2018 In the `core` branch of this repository I have a sample that works with SpringBoot 2.x - could you test with your code against the `1.3-SNAPSHOT` in the core branch? Make sure the use the `Application` config from the `springboot2` sample
