### ISSUE TITLE
Null Pointer in AwsProxyHttpServletRequestReader 

### ISSUE THREAD

**Issue by dnellutla** [awslabs/aws-serverless-java-container#241]
* Framework version: 1.3
* Implementations:  Spring Boot

## Actual behavior
   Null Pointer exception @ request.getRequestContext().getElb(). I am not setting any properties in the AWSProxyRequest object.  Are they required ?

## Full log output


16:24:07
java.lang.NullPointerException: null

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48) ~[aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28) ~[aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174) [aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209) [aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.intellicentrics.mloc.producer.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:29) [task/:na]

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]

16:24:07
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]

16:24:07
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]

16:24:07
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at java.lang.Class.forName0(Native Method) [na:1.8.0_181]

16:24:07
at java.lang.Class.forName(Class.java:348) [na:1.8.0_181]

16:24:07
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104) [LambdaJavaRTEntry-1.0.jar:na]

16:24:07
2019-02-20 16:24:07.476 ERROR 1 --- [ main] c.a.s.proxy.AwsProxyExceptionHandler : Called exception handler for:

16:24:07
java.lang.NullPointerException: null

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48) ~[aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28) ~[aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174) [aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209) [aws-serverless-java-container-core-1.3.jar:na]

16:24:07
at com.intellicentrics.mloc.producer.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:29) [task/:na]

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]

16:24:07
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]

16:24:07
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]

16:24:07
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:na]

16:24:07
at java.lang.Class.forName0(Native Method) [na:1.8.0_181]

16:24:07
at java.lang.Class.forName(Class.java:348) [na:1.8.0_181]

16:24:07
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104) [LambdaJavaRTEntry-1.0.jar:na]

16:24:07
java.lang.NullPointerException

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48)

16:24:07
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28)

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174)

16:24:07
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209)

16:24:07
at com.intellicentrics.mloc.producer.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:29)

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

16:24:07
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

16:24:07
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

16:24:07
at java.lang.reflect.Method.invoke(Method.java:498)

16:24:07
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(Ev

**Comment by sapessi** [comment]
Thanks for the report @dnellutla - I've addressed this as part of #237. I'll push a patch release over the next couple of days.

**Comment by dnellutla** [comment]
Hi @sapessi , Thank you. What version  can I use to overcome this issue ?
