### ISSUE TITLE
Spring boot application cannot access the log file

### ISSUE THREAD

**Issue by abhinav-jain09** [awslabs/aws-serverless-java-container#311]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario
 I have built the spring boot application when I try to run I get the following  exception 
## Expected behavior
it should server the request 
## Full log output

```
-rwxrwxrwx   1 abhinav          admin             5561097 Dec 19 14:35 stock-api-application.log
-rw-r-----@  1 root             admin             1000697 Dec 19 15:19 system.log
```
```
 sam local start-api -t sam.yaml
Mounting PetStoreFunction at http://127.0.0.1:3000/{proxy+} [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2019-12-19 15:17:35  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking nl.ns.sdw.stockmanagement.StreamLambdaHandler::handleRequest (java8)
2019-12-19 15:17:38 Found credentials in shared credentials file: ~/.aws/credentials
Decompressing /Users/abhinav/development/workspace/stock-api/target/stockmanagement-12.0.0-SNAPSHOT-lambda-package.zip

Fetching lambci/lambda:java8 Docker container image......
Mounting /private/var/folders/gj/tkpbbh1101v2_f5_3zpcql2h0000gp/T/tmpbthelzz2 as /var/task:ro,delegated inside runtime container
START RequestId: aacf8c54-0846-1269-7432-912fcd9c9818 Version: $LATEST
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/task/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/task/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2019-12-19 14:17:45.622  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$984ffbce] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-19 14:17:46.507 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/var/log/stock-api-application.log,true) call failed. java.io.FileNotFoundException: /var/log/stock-api-application.log (Permission denied)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:167)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:289)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:264)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:226)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:203)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:160)
        at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:23)
        at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:59)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:79)
        at nl.ns.sdw.stockmanagement.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:25)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.HandlerInfo.fromString(HandlerInfo.java:31)
        at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:92)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:334)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)

java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/var/log/stock-api-application.log,true) call failed. java.io.FileNotFoundException: /var/log/stock-api-application.log (Permission denied)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:167)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:289)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:264)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:226)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:203)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:160)
        at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:23)
        at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:59)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:79)
        at nl.ns.sdw.stockmanagement.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:25)
        ... 2 more

Exception in thread "main" java.lang.Error: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:227)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:366)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
        ... 3 more
Caused by: java.lang.RuntimeException: Unexpected status code from invocation/response: 299
        at lambdainternal.LambdaRuntime.reportDone(LambdaRuntime.java:224)
        ... 5 more
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: 
2019-12-19 15:17:47 127.0.0.1 - - [19/Dec/2019 15:17:47] "GET /pools HTTP/1.1" 502 -

```

**Comment by abhinav-jain09** [comment]
I fixed it by deleting some unwanted log configuration file

**Comment by sapessi** [comment]
Thanks for following up @abhinav-jain09 - If you are using log4j the console appender is probably the right configuration to use. The [Lambda docs have some good info](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html).
