### ISSUE TITLE
AwsProxyHttpServletRequest null pointer exception

### ISSUE THREAD

**Issue by ChrisHZ** [awslabs/aws-serverless-java-container#327]
* Framework version: 1.4

* Implementations: Jersey 
_<dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-jersey</artifactId>
            <version>1.4</version>
</dependency>_

## Scenario
Calls into lambda with no header will fail with null pointer exception. AWSProxyServletProxyRequest does not null check getting the header in _getServerName_  other similar methods in the same class do ie null means no header.
Note one successful call stop this behaviour, I presume the result of getServerName is cached.

After initially deploying API\lambda or letting lambda go cold, sending a REST request from the API Gateway console with nothing in the header box causes the lambda to null pointer, this previously worked with earlier versions of the java eg 1.1.1.

Entering absolutely any value pair in the header eg { a : 1 } so it has a header succeeds and subsequent calls no longer require the header.

From AwsProxyHttpServletRequest.getServerName ()

_String hostHeader = request.**getMultiValueHeaders()**.getFirst(HOST_HEADER_NAME);
if (hostHeader != null && SecurityUtils.isValidHost(hostHeader, request.getRequestContext().getApiId(), region)) {
            return hostHeader;
        }_

So I presume if request.getMultiValueHeaders()  return null then hostHeader should be treated as null don't attempt to call getFirst.

## Expected behavior

Acts as if no header supplied. Earlier versions of the jar eg 1.1.1 did this.

## Actual behavior

Gateway timeout. Null pointer in lambda logs.

## Steps to reproduce

After initially deploying API\lambda or letting lambda go cold, sending a REST request from the API Gateway console with nothing in the header box causes the lambda to null pointer, this previously worked with earlier versions of the java eg 1.1.1.

**Note: Any succeeding call fixes this behavior till the lambda goes cold. (bug goes away)**

## Full log output

22:44:54
java.lang.NullPointerException

22:44:54
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getServerName(AwsProxyHttpServletRequest.java:561)

22:44:54
at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.getBaseUri(JerseyHandlerFilter.java:185)

22:44:54
at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.servletRequestToContainerRequest(JerseyHandlerFilter.java:127)

22:44:54
at com.amazonaws.serverless.proxy.jersey.JerseyHandlerFilter.doFilter(JerseyHandlerFilter.java:86)

22:44:54
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)

22:44:54
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:150)

22:44:54
at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:185)

22:44:54
at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.handleRequest(JerseyLambdaContainerHandler.java:77)

22:44:54
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:211)

22:44:54
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:246)

**Comment by sapessi** [comment]
Working on version 1.5 now. We'll include this bug fix. I'll let you know here when you can test with the `1.5-SNAPSHOT` from the `v1.5` branch.

**Comment by ChrisHZ** [comment]
thanks
