### ISSUE TITLE
Quick start Spring Boot2 

### ISSUE THREAD

**Issue by vinodjayachandran** [awslabs/aws-serverless-java-container#351]
* Framework version: 1.5
* Implementations: Spring Boot 2
* OS : Mac OS

## Actual behavior - 

[ERROR] Errors: 
[ERROR]   StreamLambdaHandlerTest.setUp:32 ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

## Steps to reproduce

```
mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT \
       -DarchetypeGroupId=com.amazonaws.serverless.archetypes \
       -DarchetypeArtifactId=aws-serverless-springboot2-archetype \
       -DarchetypeVersion=1.5

mvn package
```

## Full log output

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.457 s <<< FAILURE! - in org.springframework.StreamLambdaHandlerTest
[ERROR] org.springframework.StreamLambdaHandlerTest  Time elapsed: 1.455 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.springframework.StreamLambdaHandlerTest.setUp(StreamLambdaHandlerTest.java:32)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/Users/vkv/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.6.RELEASE/spring-boot-autoconfigure-2.2.6.RELEASE.jar!/org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$EmbeddedDatabaseConfiguration.class]; nested exception is java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDatabaseConfiguration due to org/springframework/dao/DataAccessException not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.StreamLambdaHandlerTest.setUp(StreamLambdaHandlerTest.java:32)
Caused by: java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDatabaseConfiguration due to org/springframework/dao/DataAccessException not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.StreamLambdaHandlerTest.setUp(StreamLambdaHandlerTest.java:32)
Caused by: java.lang.NoClassDefFoundError: org/springframework/dao/DataAccessException
	at org.springframework.StreamLambdaHandlerTest.setUp(StreamLambdaHandlerTest.java:32)
Caused by: java.lang.ClassNotFoundException: org.springframework.dao.DataAccessException
	at org.springframework.StreamLambdaHandlerTest.setUp(StreamLambdaHandlerTest.java:32)

```

**Comment by sapessi** [comment]
Thanks for the report - we'll try to replicate today and update the issue.

**Comment by sapessi** [comment]
Did you make any changes to the code/dependencies of the application @vinodjayachandran? We just created a new app from the archetype and ran `mvn package` succesfully

**Comment by vinodjayachandran** [comment]
@sapessi On the Application.java, I had to uncomment the below line for it to work

`@ComponentScan(basePackages = "org.springframework.controller")`
