### ISSUE TITLE
Issue with API GW authentication using Cognito authorizer

### ISSUE THREAD

**Issue by davidmco65** [awslabs/aws-serverless-java-container#36]
I get this in CloudWatch when I call a service configured to use my Cognito Authorizer in API GW.  I'm passing a new, valid token received from Cognito in the appropriate header field.  I'm using 0.5-SNAPSHOT build I pulled down today from github.

```
An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: lambdainternal.util.NativeMemoryAsInputStream@2bec854f; line: 1, column: 1976] (through reference chain: com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest["requestContext"]->com.amazonaws.serverless.proxy.internal.model.ApiGatewayRequestContext["authorizer"]->com.amazonaws.serverless.proxy.internal.model.ApiGatewayAuthorizerContext["claims"])
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: lambdainternal.util.NativeMemoryAsInputStream@2bec854f; line: 1, column: 1976] (through reference chain: com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest["requestContext"]->com.amazonaws.serverless.proxy.internal.model.ApiGatewayRequestContext["authorizer"]->com.amazonaws.serverless.proxy.internal.model.ApiGatewayAuthorizerContext["claims"])
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
```

**Comment by SAPessi** [comment]
@davidmco65 can you also post a sample events here. Looks like claims is a string instead of an object or the other way around.

**Comment by davidmco65** [comment]
OK, this was my fault.  I had not quite changed all references to the framework to 0.5-SNAPSHOT.  I had one still using 0.3 and some still using 0.4.  Once I cleaned everything out and rebuilt/redeployed, it works.  
My apologies!
One question though: Is the JWT token reuseable/refreshable and what is its lifetime?

Thanks again!
David

**Comment by SAPessi** [comment]
Cool. I'll close this one then.

@davidmco65 The token lasts for 1 hour, in the response from Cognito you also get a refresh token that you can use to renew the identity and access tokens.

**Comment by davidmco65** [comment]
Any chance we can configure how long the token lasts?  I'm not getting the credentials, so I don't get the refresh token either.

**Comment by SAPessi** [comment]
You cannot configure the duration of the token. However, Cognito User Pools should return a refresh token after a successful auth: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html
