### ISSUE TITLE
Called exception handler for:  com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

### ISSUE THREAD

**Issue by shaunithvarajbekkam** [awslabs/aws-serverless-java-container#362]
* Framework version: 1.5
* Implementations:  Spring Boot 2 
## Scenario
Spring boot 2 application deploying in aws lamba with streamRequest handler

## Expected behavior
Spring boot 2 application should accept http requests in aws lambda

## Actual behavior
Getting below exception after invoking api gateway
Called exception handler for:  com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

## Steps to reproduce
1. create Spring boot 2 app with web starter and JPA data dependency.
2. create Rest controller and add get method to return hello world.
3. add following dependency for aws lambda
<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-springboot2</artifactId>
			<version>1.5</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
		</dependency>
4. package the Jar file with shade pluggin and deploy it in aws lambda. 
## Full log output


20:28:05
20:28:05.260 [main] INFO com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Starting Lambda Container Handler

20:28:06
. ____ _ __ _ _

20:28:06
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \

20:28:06
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

20:28:06
\\/ ___)| |_)| | | | | || (_| | ) ) ) )

20:28:06
' |____| .__|_| |_|_| |_\__, | / / / /

20:28:06
=========|_|==============|___/=/_/_/_/

20:28:06
:: Spring Boot ::

20:28:06
2020-07-08 20:28:06.890 INFO 1 --- [ main] lambdainternal.LambdaRTEntry : Starting LambdaRTEntry on 169.254.34.109 with PID 1 (/var/runtime/lib/LambdaJavaRTEntry-1.0.jar started by sbx_user1051 in /)

20:28:06
2020-07-08 20:28:06.892 INFO 1 --- [ main] lambdainternal.LambdaRTEntry : No active profile set, falling back to default profiles: default

20:28:08
2020-07-08 20:28:08.385 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.

20:28:08
2020-07-08 20:28:08.630 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 214ms. Found 4 JPA repository interfaces.

20:28:09
2020-07-08 20:28:09.739 INFO 1 --- [ main] c.a.s.p.i.servlet.AwsServletContext : Initializing Spring embedded WebApplicationContext

20:28:09
2020-07-08 20:28:09.739 INFO 1 --- [ main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2744 ms

20:28:10
2020-07-08 20:28:10.693 INFO 1 --- [ main] o.s.s.concurrent.ThreadPoolTaskExecutor : Initializing ExecutorService 'applicationTaskExecutor'

20:28:10
2020-07-08 20:28:10.716 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Starting...

20:28:11
2020-07-08 20:28:11.595 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Start completed.

20:28:11
2020-07-08 20:28:11.766 INFO 1 --- [ task-1] o.hibernate.jpa.internal.util.LogHelper : HHH000204: Processing PersistenceUnitInfo [name: default]

20:28:11
2020-07-08 20:28:11.898 WARN 1 --- [ main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning

20:28:12
2020-07-08 20:28:12.464 INFO 1 --- [ task-1] org.hibernate.Version : HHH000412: Hibernate ORM core version [WORKING]

20:28:13
2020-07-08 20:28:13.637 INFO 1 --- [ task-1] o.hibernate.annotations.common.Version : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}

20:28:14
2020-07-08 20:28:14.202 INFO 1 --- [ main] o.s.s.web.DefaultSecurityFilterChain : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@2d901eb0, org.springframework.security.web.context.SecurityContextPersistenceFilter@437da279, org.springframework.security.web.header.HeaderWriterFilter@550dbc7a, org.springframe

20:28:14
2020-07-08 20:28:14.641 INFO 1 --- [ task-1] org.hibernate.dialect.Dialect : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect

20:28:15
START RequestId: 6ed33c05-4bda-44cb-9aa3-9aa17bd98cbf Version: $LATEST

20:28:16
20:28:16.717 [main] INFO com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Starting Lambda Container Handler

20:28:21
. ____ _ __ _ _

20:28:21
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \

20:28:21
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

20:28:21
\\/ ___)| |_)| | | | | || (_| | ) ) ) )

20:28:21
' |____| .__|_| |_|_| |_\__, | / / / /

20:28:21
=========|_|==============|___/=/_/_/_/

20:28:21
:: Spring Boot ::

20:28:22
2020-07-08 20:28:22.436 INFO 1 --- [ main] lambdainternal.LambdaRTEntry : Starting LambdaRTEntry on 169.254.34.109 with PID 1 (/var/runtime/lib/LambdaJavaRTEntry-1.0.jar started by sbx_user1051 in /)

20:28:22
2020-07-08 20:28:22.439 INFO 1 --- [ main] lambdainternal.LambdaRTEntry : No active profile set, falling back to default profiles: default

20:28:27
2020-07-08 20:28:27.815 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.

20:28:28
2020-07-08 20:28:28.577 INFO 1 --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 579ms. Found 4 JPA repository interfaces.

20:28:32
2020-07-08 20:28:32.076 INFO 1 --- [ main] c.a.s.p.i.servlet.AwsServletContext : Initializing Spring embedded WebApplicationContext

20:28:32
2020-07-08 20:28:32.076 INFO 1 --- [ main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 9260 ms

20:28:35
2020-07-08 20:28:35.294 INFO 1 --- [ main] o.s.s.concurrent.ThreadPoolTaskExecutor : Initializing ExecutorService 'applicationTaskExecutor'

20:28:35
2020-07-08 20:28:35.360 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Starting...

20:28:38
2020-07-08 20:28:38.497 INFO 1 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Start completed.

20:28:39
2020-07-08 20:28:39.637 INFO 1 --- [ task-1] o.hibernate.jpa.internal.util.LogHelper : HHH000204: Processing PersistenceUnitInfo [name: default]

20:28:40
2020-07-08 20:28:40.235 WARN 1 --- [ main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning

20:28:41
2020-07-08 20:28:41.415 INFO 1 --- [ task-1] org.hibernate.Version : HHH000412: Hibernate ORM core version [WORKING]

20:28:45
2020-07-08 20:28:45.175 INFO 1 --- [ task-1] o.hibernate.annotations.common.Version : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}

20:28:47
2020-07-08 20:28:47.177 INFO 1 --- [ task-1] org.hibernate.dialect.Dialect : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect

20:28:50
2020-07-08 20:28:50.615 INFO 1 --- [ main] o.s.s.web.DefaultSecurityFilterChain : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@4a83a74a, org.springframework.security.web.context.SecurityContextPersistenceFilter@32502377, org.springframework.security.web.header.HeaderWriterFilter@1de5f259, org.springframe

20:28:54
2020-07-08 20:28:54.076 INFO 1 --- [ main] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…

20:28:58
2020-07-08 20:28:58.260 INFO 1 --- [ task-1] o.h.e.t.j.p.i.JtaPlatformInitiator : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]

20:28:58
2020-07-08 20:28:58.335 INFO 1 --- [ task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'

20:29:00
2020-07-08 20:29:00.937 INFO 1 --- [ main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!

20:29:01
2020-07-08 20:29:01.895 INFO 1 --- [ main] lambdainternal.LambdaRTEntry : Started LambdaRTEntry in 43.177 seconds (JVM running for 46.923)

20:29:01
2020-07-08 20:29:01.916 INFO 1 --- [ main] c.a.s.p.i.servlet.AwsServletContext : Initializing Spring DispatcherServlet 'dispatcherServlet'

20:29:01
2020-07-08 20:29:01.916 INFO 1 --- [ main] o.s.web.servlet.DispatcherServlet : Initializing Servlet 'dispatcherServlet'

20:29:02
2020-07-08 20:29:02.155 INFO 1 --- [ main] o.s.web.servlet.DispatcherServlet : Completed initialization in 239 ms

20:29:02
2020-07-08 20:29:02.635 ERROR 1 --- [ main] c.a.s.p.internal.LambdaContainerHandler : Error while handling request

20:29:02
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

20:29:02
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48) ~[task/:na]

20:29:02
at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:30) ~[task/:na]

20:29:02
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:201) [task/:na]

20:29:02
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:254) [task/:na]

20:29:02
at com.fruit.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:49) [task/:na]

20:29:02
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]

20:29:02
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]

20:29:02
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]

20:29:02
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]

20:29:02
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:354) [LambdaSandboxJava-1.0.jar:na]

20:29:02
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:909) [LambdaSandboxJava-1.0.jar:na]

20:29:02
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:na]

20:29:02
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:na]

20:29:02
at java.lang.Class.forName0(Native Method) [na:1.8.0_201]

20:29:02
at java.lang.Class.forName(Class.java:348) [na:1.8.0_201]

20:29:02
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119) [LambdaJavaRTEntry-1.0.jar:na]

20:29:02
[config.zip](https://github.com/awslabs/aws-serverless-java-container/files/4894987/config.zip)

**Comment by sapessi** [comment]
@shaunithvarajbekkam Where is the event coming from? Can you share how you are deploying the application and then testing it?

Based on your handler you should have configure an API Gateway REST API in front of the Lambda function and the invoke should come from the HTTP endpoint.

**Comment by shaunithvarajbekkam** [comment]
Thanks @sapessi, yes that's correct. I am hitting to API Gate way end point through POSTMAN client with spring basic auth enabled. 
for ex. URL. is -- https://8xhlegw7yg.execute-api.ap-south-1.amazonaws.com/api/account/fs.(this end point is Available  in controller I have shared. ). 

packaging the spring boot project as Jar with shade plugin. deploying to Lambda function. 

click [here] for repository URL. (https://github.com/shaunithvarajbekkam/fruitmarket)

**Comment by sapessi** [comment]
The only thing I can think of is that the API Gateway integration with Lambda is not configured as a "proxy". You can find the checkbox option in the integration settings for the API Gateway method.

**Comment by shaunithvarajbekkam** [comment]
thanks @sapessi, proxy configuration was the issue. It seems like I was creating lot of API gateways as it was not working. Along the way I might have unchecked it. 

Appreciate the Help.!

**Comment by sapessi** [comment]
No worries. Also feel free to pick up the SAM template from the samples in this repo to deploy - the SAM CLI will make it pretty easy.
