### ISSUE TITLE
Get request with empty request param value throws error

### ISSUE THREAD

**Issue by srp321** [awslabs/aws-serverless-java-container#365]
* Framework version: 1.5
* Implementations: Spring Boot

## Scenario
Setup Spring Boot Lambda handler for HttpApiV2 using SpringBootLambdaContainerHandler.getHttpApiV2ProxyHandler

Add a get API in controller with request parameters/query string parameters.

Deploy to AWS.
Attach API gateway (HTTP API) to Invoke lambda.
Pass only the request parameter name, and not the value associated.

## Expected behavior
Depending upon code behavior in the controller, it can return what the user has coded for the null check.

## Actual behavior
API gateway throws error 502 with gateway timeout error.
The lambda logs show below error:

`ERROR 1 --- [main] c.a.s.p.internal.LambdaContainerHandler  : Error while handling request
java.lang.ArrayIndexOutOfBoundsException: 1
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.parseRawQueryString(AwsHttpApiV2ProxyHttpServletRequest.java:492)`

## Steps to reproduce
- Add Spring Boot Lambda handler for HttpApiV2 using SpringBootLambdaContainerHandler.getHttpApiV2ProxyHandler
- Add a get API in controller with request parameters/query string parameters.

`@GetMapping("/getData")
 public ResponseEntity<ResponseBean> getComments(@RequestParam Map<String, String> requestParams) {
     String paramValue1 = Optional.ofNullable(requestParams.get("paramName1")).orElse(null);
 }`

- Deploy to AWS.
- Attach API gateway (HTTP API) to Invoke lambda.
- Pass only the request parameter name, and not the value associated.
`<api-gateway-url>/getData?paramName1=`

instead of: `<api-gateway-url>/getData?paramName1=value1`

## Full log output
`2020-07-15 14:35:07.278 ERROR 1 --- [           main] c.a.s.p.internal.LambdaContainerHandler  : Error while handling request
java.lang.ArrayIndexOutOfBoundsException: 1
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.parseRawQueryString(AwsHttpApiV2ProxyHttpServletRequest.java:492) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.<init>(AwsHttpApiV2ProxyHttpServletRequest.java:62) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:36) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:24) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:201) [task/:na]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:254) [task/:na]
at com.deere.jdf.assetmanagement.testdata.AssetLambdaHandler.handleRequest(AssetLambdaHandler.java:29) [task/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:354) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:909) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:na]
at java.lang.Class.forName0(Native Method) [na:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [na:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119) [LambdaJavaRTEntry-1.0.jar:na]
2020-07-15 14:35:07.278 ERROR 1 --- [           main] c.a.s.proxy.AwsProxyExceptionHandler     : Called exception handler for:
java.lang.ArrayIndexOutOfBoundsException: 1
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.parseRawQueryString(AwsHttpApiV2ProxyHttpServletRequest.java:492) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.<init>(AwsHttpApiV2ProxyHttpServletRequest.java:62) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:36) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:24) ~[task/:na]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:201) [task/:na]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:254) [task/:na]
at com.deere.jdf.assetmanagement.testdata.AssetLambdaHandler.handleRequest(AssetLambdaHandler.java:29) [task/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:354) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:909) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:na]
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:na]
at java.lang.Class.forName0(Native Method) [na:1.8.0_201]
at java.lang.Class.forName(Class.java:348) [na:1.8.0_201]
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119) [LambdaJavaRTEntry-1.0.jar:na]
java.lang.ArrayIndexOutOfBoundsException: 1
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.parseRawQueryString(AwsHttpApiV2ProxyHttpServletRequest.java:492)
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.<init>(AwsHttpApiV2ProxyHttpServletRequest.java:62)
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:36)
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2HttpServletRequestReader.readRequest(AwsHttpApiV2HttpServletRequestReader.java:24)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:201)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:254)
at com.deere.jdf.assetmanagement.testdata.AssetLambdaHandler.handleRequest(AssetLambdaHandler.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:354)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:909)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119)
END RequestId: 3a6eeb4b-0999-43c4-9ee9-d5b3e9e2bd8f
REPORT RequestId: 3a6eeb4b-0999-43c4-9ee9-d5b3e9e2bd8f	Duration: 2.61 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 223 MB	
`

**Comment by srp321** [comment]
The issue is already addressed in previous one: https://github.com/awslabs/aws-serverless-java-container/issues/363
