### ISSUE TITLE
awslabs/aws-serverless-java-container/springboot2 not working properly, getting ClassNotFound Exception

### ISSUE THREAD

**Issue by anandv1986** [awslabs/aws-serverless-java-container#396]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: 1.5

*Implementations:* Spring Boot

*Framework version:* SpringBoot 2.2.6.RELEASE

*Frontend service:* REST API

*Deployment method:* SAM

## Scenario
trying to deploy the SpringBoot2 project from awslabs/aws-serverless-java-container/springboot2, but its not working.

## Expected behavior
RESTapi should get invoked and proper output should be appearing in the browser.

## Actual behavior
Class not found: com.amazonaws.serverless.sample.springboot2.StreamLambdaHandler

## Steps to reproduce
Just clone the springboot2 project and deploy using SAM.
 
## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
Class not found: com.amazonaws.serverless.sample.springboot2.StreamLambdaHandler: java.lang.ClassNotFoundExceptionjava.lang.ClassNotFoundException: com.amazonaws.serverless.sample.springboot2.StreamLambdaHandler	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)	at java.lang.Class.forName0(Native Method)	at java.lang.Class.forName(Class.java:348)
```

**Comment by anandv1986** [comment]
This issue had been fixed when deployed with "Proxy Integration" option in API Gateway.
