### ISSUE TITLE
org.glassfish.jersey.model.internal.CommonConfig class not found

### ISSUE THREAD

**Issue by vinesh-sunku** [awslabs/aws-serverless-java-container#426]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: 11

*Implementations:* `Jersey`

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`

*Frontend service:* Rest API

*Deployment method:* Console

## Scenario
I am trying create a test APIs to work by integrating with rest API gateway and lambda.

## Expected behavior
I can see that class present in the jar provided. I have provided the required dependencies

## Actual behavior
It fails with 502 class not found. Expected to return 200 or 404.

## Steps to reproduce
```
package org.example.apis;

import com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;
import org.glassfish.jersey.jackson.JacksonFeature;
import org.glassfish.jersey.server.ResourceConfig;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class ProxyRequestHandler implements RequestStreamHandler {

    private static final ResourceConfig jerseyApplication = new ResourceConfig().packages("org.example.apis")
            .register(JacksonFeature.class);

    private static final JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
        handler.proxyStream(inputStream, outputStream, context);
    }
}
```
pom.xml file
```
 <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.26</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-jersey</artifactId>
            <version>[0.1,)</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>3.0.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>3.0.2</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jersey</groupId>
            <artifactId>jax-rs-ri</artifactId>
            <version>2.0-rc1</version>
        </dependency>
    </dependencies>
```

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```

Error loading class org.example.apis.ProxyRequestHandler: 'void org.glassfish.jersey.model.internal.CommonConfig.<init>(javax.ws.rs.RuntimeType, java.util.function.Predicate)': java.lang.NoSuchMethodErrorjava.lang.NoSuchMethodError: 'void org.glassfish.jersey.model.internal.CommonConfig.<init>(javax.ws.rs.RuntimeType, java.util.function.Predicate)'	
at org.glassfish.jersey.server.ResourceConfig$State.<init>(ResourceConfig.java:93)	
at org.glassfish.jersey.server.ResourceConfig.<init>(ResourceConfig.java:331)	
at org.example.apis.ProxyRequestHandler.<clinit>(ProxyRequestHandler.java:17)	
at java.base/java.lang.Class.forName0(Native Method)	
at java.base/java.lang.Class.forName(Unknown Source) |

```

**Comment by deki** [comment]
Hi,
why are you using org.glassfish.jersey:jax-rs-ri as dependency?
Are you planning to use Jersey version 2 or 3?

You can find a working sample with Jersey 2 in: https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/jersey/pet-store/
