### ISSUE TITLE
Accept-Encoding header causes Spring to throw 500 errors

### ISSUE THREAD

**Issue by joeyvmason** [awslabs/aws-serverless-java-container#5]
If `Content-Type` request header is `application/json` instead of `application/json;charset=UTF`, then providing `Accept-Encoding` values other than `UTF-8` (e.g. `gzip, deflate, sdch`) will result in 500 errors when running on AWS Lambda. Have not been able to reproduce this locally, but it happens without fail when run on AWS Lambda.

Full stack trace: 

```
java.nio.charset.IllegalCharsetNameException: gzip, deflate, sdch
java.nio.charset.Charset.checkName(Charset.java:315) java.nio.charset.Charset.lookup2(Charset.java:484)
java.nio.charset.Charset.lookup(Charset.java:464)
java.nio.charset.Charset.forName(Charset.java:528) ~[na:1.8.0_101]
	at org.springframework.http.server.ServletServerHttpRequest.getHeaders(ServletServerHttpRequest.java:131) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:167) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:150) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:128) ~[task/:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[task/:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:160) ~[task/:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:129) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[task/:na]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[task/:na]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[task/:na]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[task/:na]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [task/:na]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [task/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688) [task/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [task/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770) [task/:na]
	at com.amazonaws.serverless.proxy.spring.LambdaSpringApplicationInitializer.dispatch(LambdaSpringApplicationInitializer.java:82) [task/:na]
	at com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler.handleRequest(SpringLambdaContainerHandler.java:136) [task/:na]
	at com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler.handleRequest(SpringLambdaContainerHandler.java:37) [task/:na]
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:88) [task/:na]
	at com.joeyvmason.serverless.spring.application.LambdaHandler.handleRequest(LambdaHandler.java:33) [task/:na]
	at com.joeyvmason.serverless.spring.application.LambdaHandler.handleRequest(LambdaHandler.java:14) [task/:na]
	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:375) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:1139) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:285) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:57) [LambdaSandboxJava-1.0.jar:na]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_101]
	at java.lang.Class.forName(Class.java:348) [na:1.8.0_101]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94) [LambdaJavaRTEntry-1.0.jar:na]
INFO; Jan 18, 2017 01:49:51 AM; tid:[main]; LoggingInterceptor afterCompletion; Request completed with Status(500)
```

**Comment by SAPessi** [comment]
Thanks, I'll take a look

**Comment by SAPessi** [comment]
Fix and unit test committed
