### ISSUE TITLE
stuck in this solution ... help!!!

### ISSUE THREAD

**Issue by shaklenahmad** [awslabs/aws-serverless-java-container#508]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `eg. 1.5`

*Implementations:* `Jersey / Spring / Spring Boot / Spring Boot 2 / Spark`

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`

*Frontend service:* `REST API / HTTP API / ALB`

*Deployment method:* `eg SAM, Serverless Framework, Console`

## Scenario
*Describe what you are trying to accomplish*

## Expected behavior
*Describe how you would expect the application to behave*

## Actual behavior
*Describe what you are seeing instead*

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here*

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
logs
```

**Comment by deki** [comment]
Hi @shaklenahmad,
please add more details to the issue, otherwise we are unable to help you.

**Comment by shaklenahmad** [comment]
i am using this code to initialized my spring boot application which is deployed on aws lambda but my server is not getting started .. even though i have set the intialisation 20sec more but still getting the error . i have followed this link https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot2 . 

package com.marketplaceupdater.jimintegration;

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.LambdaContainerHandler;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler;
import com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.Instant;

public class StreamLambdaHandler implements RequestStreamHandler {
    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

    Logger logger= LoggerFactory.getLogger(StreamLambdaHandler.class);

    public StreamLambdaHandler() throws ContainerInitializationException {
        try {
            long startTime = Instant.now().toEpochMilli();
            logger.info("setting initialisation time -20sec begins");
            // by setting this value to 20_000 the framework will wait for an additional 20 seconds
            // on top of the default 10 initialization time.
            LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);

            logger.info("setting initialisation time -20sec ends ");

            handler = new SpringBootProxyHandlerBuilder<AwsProxyRequest>()
                    .defaultProxy()
                    .asyncInit()
                    .springBootApplication(JimIntegrationApplication.class)
                    .buildAndInitialize();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {

        logger.info("hi from handleRequest ");

        handler.proxyStream(inputStream, outputStream, context);
    }
}



my logs are this ... please help 



INIT_START Runtime Version: java:8.v14	Runtime Version ARN: arn:aws:lambda:eu-north-1::runtime:976f6b03f8ebcf9a902c3d59a05ba4b7c260b2841a5a10b307bb8bbd15e34a03
--
Picked up JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
12:48:45.397 [main] INFO com.marketplaceupdater.jimintegration.StreamLambdaHandler - setting initialisation time -20sec begins
12:48:45.594 [main] INFO com.marketplaceupdater.jimintegration.StreamLambdaHandler - setting initialisation time -20sec ends
12:48:45.616 [main] INFO com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Starting Lambda Container Handler
12:48:45.784 [Thread-0] INFO com.amazonaws.serverless.proxy.AsyncInitializationWrapper - Starting async initializer
12:48:45.784 [main] INFO com.amazonaws.serverless.proxy.AsyncInitializationWrapper - Async initialization will wait for 9113ms (init grace time is configured to 150)
.   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ \| '_ \| '_\| \| '_ \/ _` \| \ \ \ \
\\/  ___)\| \|_)\| \| \| \| \| \|\| (_\| \|  ) ) ) )
'  \|____\| .__\|_\| \|_\|_\| \|_\__, \| / / / /
=========\|_\|==============\|___/=/_/_/_/
:: Spring Boot ::                (v2.7.9)
2023-03-04 12:48:46,423 [INFO] org.springframework.boot.SpringApplication [Thread-0] Starting application using Java 1.8.0_322 on 169.254.104.9 with PID 8 (started by sbx_user1051 in /var/task)
2023-03-04 12:48:46,424 [INFO] org.springframework.boot.SpringApplication [Thread-0] No active profile set, falling back to 1 default profile: "default"
2023-03-04 12:48:47,157 [INFO] org.springframework.data.repository.config.RepositoryConfigurationDelegate [Thread-0] Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-03-04 12:48:47,264 [INFO] org.springframework.data.repository.config.RepositoryConfigurationDelegate [Thread-0] Finished Spring Data repository scanning in 96 ms. Found 5 JPA repository interfaces.
2023-03-04 12:48:47,657 [INFO] com.amazonaws.serverless.proxy.internal.servlet.AwsServletContext [Thread-0] Initializing Spring embedded WebApplicationContext
2023-03-04 12:48:47,657 [INFO] org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext [Thread-0] Root WebApplicationContext: initialization completed in 1187 ms
2023-03-04 12:48:47,895 [INFO] org.hibernate.jpa.internal.util.LogHelper [Thread-0] HHH000204: Processing PersistenceUnitInfo [name: default]
2023-03-04 12:48:47,963 [INFO] org.hibernate.Version [Thread-0] HHH000412: Hibernate ORM core version 5.6.15.Final
2023-03-04 12:48:48,154 [INFO] org.hibernate.annotations.common.Version [Thread-0] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-03-04 12:48:48,267 [INFO] com.zaxxer.hikari.HikariDataSource [Thread-0] HikariPool-1 - Starting...
2023-03-04 12:48:50,739 [INFO] com.zaxxer.hikari.HikariDataSource [Thread-0] HikariPool-1 - Start completed.
2023-03-04 12:48:50,777 [INFO] org.hibernate.dialect.Dialect [Thread-0] HHH000400: Using dialect: org.hibernate.dialect.MySQL57Dialect
2023-03-04 12:48:54,898 [INFO] com.amazonaws.serverless.proxy.AsyncInitializationWrapper [main] Initialization took longer than 10000, setting new CountDownLatch and continuing in event handler
START RequestId: 6db605fe-4254-4773-9a79-f65851201865 Version: $LATEST
2023-03-04 12:48:54,904 [INFO] com.marketplaceupdater.jimintegration.StreamLambdaHandler [main] hi from handleRequest
2023-03-04 12:49:14,931 [ERROR] com.amazonaws.serverless.proxy.internal.LambdaContainerHandler [main] Error while handling request
com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 20000ms timeout
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:210)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
at com.marketplaceupdater.jimintegration.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:356)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:349)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:70)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
2023-03-04 12:49:14,932 [ERROR] com.amazonaws.serverless.proxy.AwsProxyExceptionHandler [main] Called exception handler for:
com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 20000ms timeout
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:210)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
at com.marketplaceupdater.jimintegration.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:356)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:349)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:70)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 20000ms timeout
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:210)
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
at com.marketplaceupdater.jimintegration.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:356)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:349)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:70)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
END RequestId: 6db605fe-4254-4773-9a79-f65851201865
REPORT RequestId: 6db605fe-4254-4773-9a79-f65851201865	Duration: 20044.48 ms	Billed Duration: 20045 ms	Memory Size: 2048 MB	Max Memory Used: 270 MB	Init Duration: 9902.12 ms

**Comment by shaklenahmad** [comment]
update now i am not getting the exception but still my server not getting started .. this is my logs now ...


<html>
<body>


:: Spring Boot ::                (v2.7.9)
--
2023-03-05 05:44:40,902 [INFO] lambdainternal.LambdaRTEntry [main] Starting LambdaRTEntry using Java 1.8.0_322 on 169.254.48.189 with PID 8 (/var/runtime/lib/LambdaJavaRTEntry-byol.jar started by sbx_user1051 in /var/task)
2023-03-05 05:44:40,903 [INFO] lambdainternal.LambdaRTEntry [main] No active profile set, falling back to 1 default profile: "default"
2023-03-05 05:44:41,597 [INFO] org.springframework.data.repository.config.RepositoryConfigurationDelegate [main] Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-03-05 05:44:41,698 [INFO] org.springframework.data.repository.config.RepositoryConfigurationDelegate [main] Finished Spring Data repository scanning in 86 ms. Found 5 JPA repository interfaces.
2023-03-05 05:44:42,097 [INFO] com.amazonaws.serverless.proxy.internal.servlet.AwsServletContext [main] Initializing Spring embedded WebApplicationContext
2023-03-05 05:44:42,097 [INFO] org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext [main] Root WebApplicationContext: initialization completed in 1154 ms
2023-03-05 05:44:42,321 [INFO] org.hibernate.jpa.internal.util.LogHelper [main] HHH000204: Processing PersistenceUnitInfo [name: default]
2023-03-05 05:44:42,385 [INFO] org.hibernate.Version [main] HHH000412: Hibernate ORM core version 5.6.15.Final
2023-03-05 05:44:42,569 [INFO] org.hibernate.annotations.common.Version [main] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-03-05 05:44:42,683 [INFO] com.zaxxer.hikari.HikariDataSource [main] HikariPool-1 - Starting...
2023-03-05 05:44:45,032 [INFO] com.zaxxer.hikari.HikariDataSource [main] HikariPool-1 - Start completed.
2023-03-05 05:44:45,065 [INFO] org.hibernate.dialect.Dialect [main] HHH000400: Using dialect: org.hibernate.dialect.MySQL57Dialect


</body>
</html>

**Comment by deki** [comment]
I don't see any issues in the latest logfile. Please try the petstore sample https://github.com/awslabs/aws-serverless-java-container/tree/main/samples/springboot2/pet-store or share a small project to reproduce the issue.

**Comment by deki** [comment]
No further feedback therefore closing it. Feel free to reach out to us directly https://aws.amazon.com/contact-us/ or reopen this issue with additional details.
