### ISSUE TITLE
Exception when our API path ends with the <x>.<y> (.../versions/v1.0) format? 

### ISSUE THREAD

**Issue by ashokkumar-subburaj** [awslabs/aws-serverless-java-container#571]
*Serverless Java Container version*: `1.9`

*Implementations:* `Spring Boot 2`

*Framework version:* `SpringBoot 2.7.7.RELEASE`

*Frontend service:* `REST API`

*Deployment method:* `SAM`

*Java version* : `Java11`

## Scenario
We have few endpoints implemented one of which endpoint ends with the format `(BASE_URL)/versions/*.* `. For example as mentioned in the summary our url ends with the GET `{BASE_URL}/.../versions/v1.0`. 
Our get versions spring boot implementation code is something like the below.
`@GetMapping(value = "/../{path_variable}/versions/{input}")`
Container is trying to resolve this as a file rather than the normal REST endpoint and failing with the exception.

## Expected behavior
It should resolve correctly and implementation code should be called.

## Actual behavior
`java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
at javax.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:100)
at com.amazonaws.serverless.proxy.internal.servlet.AwsServletContext.getMimeType(AwsServletContext.java:137)
`

## Full log output
*java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
at javax.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:100)
at com.amazonaws.serverless.proxy.internal.servlet.AwsServletContext.getMimeType(AwsServletContext.java:137)
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.resolveMediaType(AbstractMessageConverterMethodProcessor.java:481)
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.safeExtension(AbstractMessageConverterMethodProcessor.java:474)
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.addContentDispositionHeader(AbstractMessageConverterMethodProcessor.java:449)
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:288)
at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219)
at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:428)
at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:75)
at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:142)
at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80)
at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1331)
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1142)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager$ServletExecutionFilter.doFilter(FilterChainManager.java:374)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at com.trimble.tcp.events.marketplace.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:61)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at com.trimble.tcp.events.marketplace.filter.TraceIdFilter.doFilter(TraceIdFilter.java:38)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:90)
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:156)*

**Comment by mbfreder** [comment]
Thanks for reporting this issue. We are looking into it.

**Comment by valerena** [comment]
Hi @ashokkumar-subburaj. I was trying to reproduce your error, but I wasn't able to do so with the setup you described in the description. Do you have a full project where the problem can be reproduced so we can try it out? (Or maybe try to reproduce starting with our [sample project](https://github.com/awslabs/aws-serverless-java-container/tree/1.x/samples/springboot2/pet-store/)) There might be come other configuration that's causing this issue. 


On a side note, and I don't know if it will help in your case, but the exact error that you're seeing also seems to be related to a missing dependency as described here: https://github.com/jakartaee/jaf-api/issues/60. You could try to add what's mention there (adding the dependency `com.sun.activation:jakarta.activation`) to see if then your application works correctly, while we try to reproduce the rest of your problem.

**Comment by ashokkumar-subburaj** [comment]
I'll try adding this dependency and update here.

**Comment by ashokkumar-subburaj** [comment]
Sorry for the late reply. Adding the above dependency `com.sun.activation:jakarta.activation` worked for me. Thanks for the help @mbfreder
