### ISSUE TITLE
Exception running CognitoAuthorizerClaimsTest.claims_dateParse_issueTime

### ISSUE THREAD

**Issue by 1123** [awslabs/aws-serverless-java-container#96]
This seems to be a very promising project. Thanks for your work. Yet I cannot build it. Here is the first test that fails for me: 

```
java.time.format.DateTimeParseException: Text 'Mon Apr 17 23:12:49 UTC 2017' could not be parsed at index 2

	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at com.amazonaws.serverless.proxy.model.CognitoAuthorizerClaimsTest.claims_dateParse_issueTime(CognitoAuthorizerClaimsTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at 

 com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Seems like my DateTimeFormatter does does not match `EEE` with `Mon` in the test case. If I remove this part of the Date and the pattern, then parsing works. 

Any ideas?

**Comment by 1123** [comment]
Turns out I need to add `.withLocale(Locale.ENGLISH)` to the initialization of the DateTimeFormatter: 

```
    static final DateTimeFormatter TOKEN_DATE_FORMATTER = DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss zzz yyyy").withLocale(Locale.ENGLISH);

```

**Comment by SAPessi** [comment]
Thanks for the fix @1123, good catch! I'm making some changes on another branch and I'll get it all merged together over the next few days!
